### ISSUE TITLE
does it remove animation?

### ISSUE THREAD

**Issue by demidovakatya** [leo/phoenix#1]
Hey there, 
The idea of decluttering twitter (and the whole web!) is awesome. I hate it when twitter.com turns into some kind of disneyland on heroine – it's "amusing" but so.fcking.slow.
So I wonder if your extension removes that annoying animation.

**Comment by leo** [comment]
Which animation do you mean? :blush:

**Comment by demidovakatya** [comment]
it's hard for me to explain it >_>
but, well, for example: header image hides at profile page when you scroll down; expanding tweets and loading tweets. but I'm not sure it's animation anymore :hamster:

**Comment by leo** [comment]
Those animations usually shouldn't slow down the site (for me, everything works fine in this area) and I'm honestly not intending to disable them. Why don't you simply try it out? :smile_cat:
